# Generated by Django 5.0 on 2023-12-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plumbing',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
