# Generated by Django 5.0 on 2023-12-09 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0002_alter_plumbing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plumbingdetails',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='plumbing.plumbing', verbose_name='Детели'),
        ),
    ]
