# Generated by Django 5.0 on 2023-12-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0004_alter_plumbing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plumbing',
            name='link',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='plumbing',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
    ]
